### ISSUE TITLE
Clang Format Bugs/todo

### ISSUE THREAD

**Issue by quentin452** [quentin452/CatzEngine#42]
- [x] todo add undo /redo support for clang format
- [x] todo move clang format and auto save script to "File" instead of "Code Editor Option" tab
- [x] todo fix the command get executed multiple times caused by keys handling
- [x] sometimes clang command are blocked for some reason
- [x] #48
- [x] #46
- [x] #49
